[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = [
  "chmod +x ./mvnw",
  "./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"
]

[start]
cmd = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar"